FORMAT: 1A

# Acast

Here are some endpoints we use to validate our player logic
            
## Root collection [/]

### Load Episode 0 [GET]

+ Response 200 (application/json)

        {
          "author": "Kristoffer Triumf",
          "modified": "2016-08-17T20:04:34.849Z",
          "created": "2016-08-17T19:46:10.975Z",
          "publishingDate": "2016-08-21T04:00:00Z",
          "url": "-242-lindamisslikarlsson",
          "tags": [
            "miss",
            "li",
            "linda",
            "karlsson",
            "kristoffer",
            "triumf"
          ],
          "image": "https://acastprod.blob.core.windows.net:443/media/v1/964df327-ef67-4420-bf84-78d56d3f7908/varvet-242-miss-li-irzbqt1e.jpg",
          "duration": 5210.4080000000004,
          "channel": {
            "author": "Kristoffer Triumf",
            "modified": "2016-08-30T19:11:15.874Z",
            "exclusive": false,
            "publishingDate": "2014-04-20T21:10:32Z",
            "ownerName": "Kristoffer Triumf",
            "url": "varvet",
            "summary": "Kristoffer Triumf med en intressant gäst, så enkelt är det.",
            "image": "https://acastprod.blob.core.windows.net:443/media/v1/bf4e5114-fe02-4088-9a07-c1b81a3c615a/varvet14001400.jpg",
            "language": "sv",
            "created": "2014-04-22T15:55:44.929Z",
            "hidden": false,
            "hosted": true,
            "name": "Värvet",
            "id": "bf4e5114-fe02-4088-9a07-c1b81a3c615a",
            "ownerEmail": "varvet@triumf.se",
            "subtitle": "Kristoffer Triumf, det vill säga jag, möter en gäst i veckan och en ganska lång intervju brukar uppstå. Håll till godo!  ",
            "rating": "no",
            "categories": [
              "Business",
              "Comedy",
              "TV & Film"
            ],
            "description": "Kristoffer Triumf, det vill säga jag, möter en gäst i veckan och en ganska lång intervju brukar uppstå. Håll till godo!"
          },
          "blings": [
            {
              "start": 0,
              "id": "8656ed4d-0cad-4087-a146-725f72e1d942",
              "namespace": "com.acast.blings",
              "duration": 3.0,
              "type": "BlingAudio",
              "body": {
                "media": "https://github.com/JagCesar/acast-apiary/raw/master/episode.mp3"
              },
              "audio": "https://github.com/JagCesar/acast-apiary/raw/master/episode.mp3"
            },
            {
              "thumbnail": "https://acastprod.blob.core.windows.net:443/media/v1/1a301c85-ccf9-4439-b629-c3b5e17be10b/ska-rmavbild2016-08-17kl.21.56.23-irzbk15i.png",
              "start": 713,
              "id": "1a301c85-ccf9-4439-b629-c3b5e17be10b",
              "namespace": "com.acast.blings",
              "image": "https://acastprod.blob.core.windows.net:443/media/v1/1a301c85-ccf9-4439-b629-c3b5e17be10b/ska-rmavbild2016-08-17kl.21.56.23-irzbk15i.png",
              "duration": 30,
              "type": "BlingLink",
              "body": {
                "linkurl": "http://www.op.se/noje/musik/underkant-miss-li"
              },
              "url": "http://www.op.se/noje/musik/underkant-miss-li"
            },
            {
              "start": 0,
              "id": "84ef88e0-b452-40ec-bbf6-525f4ff5014a",
              "placement": "preroll",
              "count": 1,
              "namespace": "de.adtech.blings",
              "duration": 0,
              "lostAdId": "123",
              "type": "BlingAdtechAd",
              "body": {
                "placement": "preroll"
              },
              "minimizedVastUrl": "http://private-c2aeb-acast.apiary-mock.com/minVastAd",
              "maximizedVastUrl": "http://private-c2aeb-acast.apiary-mock.com/maxVastAd"
            },{
              "start": 2605.2040000000002,
              "id": "28522580-365d-48ad-a616-e93cf0a30e16",
              "placement": "midroll",
              "count": 2,
              "namespace": "de.adtech.blings",
              "duration": 0,
              "lostAdId": "123",
              "type": "BlingAdtechAd",
              "body": {
                "placement": "midroll"
              },
              "minimizedVastUrl": "http://private-c2aeb-acast.apiary-mock.com/minVastAd",
              "maximizedVastUrl": "http://private-c2aeb-acast.apiary-mock.com/maxVastAd"
            },
            {
              "start": 5210.4080000000004,
              "id": "f78ffd98-76d4-4de1-8320-ada7a2a67a33",
              "placement": "postroll",
              "count": 1,
              "namespace": "de.adtech.blings",
              "duration": 0,
              "lostAdId": "123",
              "type": "BlingAdtechAd",
              "body": {
                "placement": "postroll"
              },
              "minimizedVastUrl": "http://private-c2aeb-acast.apiary-mock.com/minVastAd",
              "maximizedVastUrl": "http://private-c2aeb-acast.apiary-mock.com/maxVastAd"
            },
            {
              "start": 0,
              "id": "0637c1d0-7118-11e6-93aa-53eb95f35026",
              "placement": "preroll",
              "count": 1,
              "namespace": "de.adtech.blings",
              "duration": 0,
              "lostAdId": "123",
              "type": "BlingAdtechSponsor",
              "vastUrl": "http://private-c2aeb-acast.apiary-mock.com/vastSpons"
            },
            {
              "start": 2605.2040000000002,
              "id": "0637c1d1-7118-11e6-93aa-53eb95f35026",
              "placement": "midroll",
              "count": 1,
              "namespace": "de.adtech.blings",
              "duration": 0,
              "lostAdId": "123",
              "type": "BlingAdtechSponsor",
              "vastUrl": "http://private-c2aeb-acast.apiary-mock.com/vastSpons"
            },
            {
              "start": 5210.4079000000002,
              "id": "0637c1d2-7118-11e6-93aa-53eb95f35026",
              "placement": "postroll",
              "count": 1,
              "namespace": "de.adtech.blings",
              "duration": 0,
              "lostAdId": "123",
              "type": "BlingAdtechSponsor",
              "vastUrl": "http://private-c2aeb-acast.apiary-mock.com/vastSpons"
            }
          ],
          "hosted": true,
          "name": "#242: Linda \"Miss Li\" Karlsson",
          "id": "964df327-ef67-4420-bf84-78d56d3f7908",
          "contentLength": 83366528,
          "subtitle": "Det svåra tvåhundrafyrtioandra avsnittet med artisten och låtskrivaren Linda ‘Miss Li’ Karlsson. Vi pratade om Pokémon Go, att ta paus som artist, skriva och spela in ett album på en vecka, major-skivbolag, älskade ångestperioder, terapi, recensioner, styla artister, en enorm garderob, att skriva åt andra artister, kreativa dippar, att nedvärdera sig själv, Zlatan, att fira tioårsjubileum, Borlänge, Rihanna och givetvis en hel del om det historiska i ordet flegmatisk.\nSamtalsledare: Kristoffer Triumf.\nProducent: David Mehr.\nDistribution: Acast.",
          "contentType": "audio/mpeg",
          "lastPublished": "2016-08-17T20:04:35.17Z",
          "rating": "no",
          "channelId": "bf4e5114-fe02-4088-9a07-c1b81a3c615a",
          "description": "Det svåra tvåhundrafyrtioandra avsnittet med artisten och låtskrivaren Linda ‘Miss Li’ Karlsson. Vi pratade om att ta paus som artist, skriva och spela in ett album på en vecka, major-skivbolag, älskade ångestperioder, terapi, recensioner, styla artister, en enorm garderob, att skriva åt andra artister, kreativa dippar, att nedvärdera sig själv, Zlatan, att fira tioårsjubileum, Borlänge, Rihanna och givetvis en hel del om det historiska i ordet flegmatisk.\nSamtalsledare: Kristoffer Triumf.\nProducent: David Mehr.\nDistribution: Acast."
        }

## Minimized ad vast [/minVastAd]

### Load minimized ad vast [GET]

+ Response 200 (application/xml)

        <?xml version="1.0" encoding="UTF-8"?>
        <VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="2.0.1">
                <Ad id="15741011">
                    <InLine>
                        <AdSystem>ADTECH</AdSystem>
                        <AdTitle>ADTECH AD AdId=15741011, CreativeId=1157524, AssetId=110345565</AdTitle>
                        <Impression><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_START;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Impression>

                        <Creatives>
                            <Creative id="1157524">
            <Linear>
        <Duration>00:00:11</Duration>
        <TrackingEvents>
        <Tracking event="acceptInvitation"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_ACCEPTINVITATION;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="close"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_CLOSE;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="collapse"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_COLLAPSE;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="complete"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_END;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="creativeView"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_CREATIVEVIEW;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="expand"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_EXPAND;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="firstQuartile"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_25;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="fullscreen"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_FULLSCREEN;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="midpoint"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_MID;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="mute"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_MUTE;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="pause"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_PAUSE;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="resume"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_RESUME;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="rewind"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_REWIND;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="thirdQuartile"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_75;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="unmute"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102397/0/0/AdId=15741011;CreativeId=1157524;BnId=1;rmeventtype=VID_UNMUTE;imptype=2;refsequenceid=1551903201;refseqid2=/MiDOkzAeFA;ku=4363153;key=varvet]]></Tracking>
        </TrackingEvents>

        <VideoClicks>
            <ClickThrough><![CDATA[http://adserver.adtech.de/adlink/1539/5102397/0/3548/AdId=15741011;BnId=1;itime=827626438;ku=4363153;key=varvet;nodecode=yes;link=]]></ClickThrough>
            
        </VideoClicks>

        <MediaFiles>
        <MediaFile delivery="progressive" bitrate="0" width="128" height="96" type="audio/mp3">
        <![CDATA[https://github.com/JagCesar/acast-apiary/raw/master/ad.mp3]]>
        </MediaFile>
        </MediaFiles>

            </Linear>
        </Creative>

                            
                            
                        </Creatives>
                
                    </InLine>
                </Ad>
        </VAST>

## Maximized ad vast [/maxVastAd]

### Load maximized ad vast [GET]

+ Response 200 (application/xml)

        <?xml version="1.0" encoding="UTF-8"?>
        <VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="2.0.1">
                <Ad id="15414733">
                    <InLine>
                        <AdSystem>ADTECH</AdSystem>
                        <AdTitle>ADTECH AD AdId=15414733, CreativeId=1145674, AssetId=110260105</AdTitle>
                        <Impression><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_START;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Impression>

                        <Creatives>
                            <Creative id="1145674">
            <Linear>
        <Duration>00:00:20</Duration>
        <TrackingEvents>
        <Tracking event="acceptInvitation"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_ACCEPTINVITATION;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="close"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_CLOSE;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="collapse"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_COLLAPSE;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="complete"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_END;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="creativeView"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_CREATIVEVIEW;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="expand"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_EXPAND;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="firstQuartile"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_25;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="fullscreen"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_FULLSCREEN;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="midpoint"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_MID;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="mute"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_MUTE;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="pause"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_PAUSE;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="resume"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_RESUME;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="rewind"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_REWIND;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="thirdQuartile"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_75;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="unmute"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5102396/0/0/AdId=15414733;CreativeId=1145674;BnId=10;rmeventtype=VID_UNMUTE;imptype=2;refsequenceid=1484795682;refseqid2=2E4COEzAAAA;ku=4363153;key=varvet]]></Tracking>
        </TrackingEvents>

        <VideoClicks>
            <ClickThrough><![CDATA[http://adserver.adtech.de/adlink/1539/5102396/0/3548/AdId=15414733;BnId=10;itime=827736998;ku=4363153;key=varvet;nodecode=yes;link=http://track.adform.net/C/?bn=13692555]]></ClickThrough>
            
        </VideoClicks>

        <MediaFiles>
        <MediaFile delivery="progressive" bitrate="0" width="128" height="96" type="audio/mp3">
        <![CDATA[https://github.com/JagCesar/acast-apiary/raw/master/ad.mp3]]>
        </MediaFile>
        </MediaFiles>

            </Linear>
        </Creative>

                            <Creative id="1145674">
            <CompanionAds>
        <Companion width="320" height="320" id="companion_left">
        <HTMLResource><![CDATA[<img src="http://adserver.adtech.de/adserv/3.0/1539/5132490/0/2804/creativeid=1145674;bnid=13;adid=15414733;itime=827736998;ku=4363153;key=varvet" width="320" height="320">]]></HTMLResource>
        <CompanionClickThrough><![CDATA[http://adserver.adtech.de/adlink/1539/5132490/0/2804/AdId=15414733;BnId=13;itime=827736998;ku=4363153;key=varvet;nodecode=yes;link=]]></CompanionClickThrough>

        </Companion>
            </CompanionAds>
        </Creative>

                            
                        </Creatives>
                
                    </InLine>
                </Ad>
        </VAST>

## Ad sponsor vast [/vastSpons]

### Load ad sponsor vast [GET]

+ Response 200 (application/xml)

        <?xml version="1.0" encoding="UTF-8"?>
        <VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="2.0.1">
                <Ad id="15713543">
                    <InLine>
                        <AdSystem>ADTECH</AdSystem>
                        <AdTitle>ADTECH AD AdId=15713543, CreativeId=1155448, AssetId=110345091</AdTitle>
                        <Impression><![CDATA[http://track.adform.net/adfserve/?bn=12468774;1x1inv=1;srctype=3;ord=827819380]]></Impression>
        <Impression><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_START;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Impression>

                        <Creatives>
                            <Creative id="1155448">
            <Linear>
        <Duration>00:01:10</Duration>
        <TrackingEvents>
        <Tracking event="acceptInvitation"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_ACCEPTINVITATION;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="close"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_CLOSE;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="collapse"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_COLLAPSE;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="complete"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_END;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="creativeView"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_CREATIVEVIEW;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="expand"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_EXPAND;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="firstQuartile"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_25;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="fullscreen"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_FULLSCREEN;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="midpoint"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_MID;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="mute"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_MUTE;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="pause"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_PAUSE;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="resume"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_RESUME;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="rewind"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_REWIND;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="thirdQuartile"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_75;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        <Tracking event="unmute"><![CDATA[http://adserver.adtech.de/rmevent/3/1539/5567616/0/0/AdId=15713543;CreativeId=1155448;BnId=4;rmeventtype=VID_UNMUTE;imptype=2;refsequenceid=1568683448;refseqid2=7LNEOszAnCA;ku=4363153;key=varvet]]></Tracking>
        </TrackingEvents>

        <VideoClicks>
            <ClickThrough><![CDATA[http://adserver.adtech.de/adlink/1539/5567616/0/3548/AdId=15713543;BnId=4;itime=827819380;ku=4363153;key=varvet;nodecode=yes;link=https://swedbank.priceless.com/]]></ClickThrough>
            
        </VideoClicks>

        <MediaFiles>
        <MediaFile delivery="progressive" bitrate="0" width="128" height="96" type="audio/mp3">
        <![CDATA[https://github.com/JagCesar/acast-apiary/raw/master/spons.mp3]]>
        </MediaFile>
        </MediaFiles>

            </Linear>
        </Creative>

                            <Creative id="1155448">
            <CompanionAds>
        <Companion width="320" height="320" id="companion_left">
        <HTMLResource><![CDATA[<img src="http://adserver.adtech.de/adserv/3.0/1539/5567619/0/2804/creativeid=1155448;bnid=2;adid=15713543;itime=827819380;ku=4363153;key=varvet" width="320" height="320">]]></HTMLResource>
        <CompanionClickThrough><![CDATA[http://adserver.adtech.de/adlink/1539/5567619/0/2804/AdId=15713543;BnId=2;itime=827819380;ku=4363153;key=varvet;nodecode=yes;link=]]></CompanionClickThrough>

        </Companion>
            </CompanionAds>
        </Creative>

                            
                        </Creatives>
                
                    </InLine>
                </Ad>
        </VAST>
